server:
  port: 8888
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        #access: http://localhost:8888/application_name/somepath
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#        - id: dominator-api
#          uri: lb://dominator-api
#          predicates:
#            - Path=/requirement/**
        #access: http://localhost:8888/api/somepath
#        - id: dominator-api
#          uri: lb://dominator-api
#          predicates:
#            - Path=/api/**
#          filters:
#            - RewritePath=/api(?<segment>/?.*), $\{segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug
